### ISSUE TITLE
Set pretty console printing with a separate env variable

### ISSUE THREAD

**Issue by ku3o** [kiwicom/kiwi-structlog-config#3]
I found two development pattern where it would make sense to set [ConsoleRenderer](kw/structlog_config/config.py#L31) separately from `DEBUB` level:

1. In production for a short period of time, I need to increase a logging level to `DEBUG `, but at the same time, I don't want to break log parsing.

2. During local development, I don't want to see `DEBUG` message, but still, want to comfortably read log messages. 

Thoughts @underyx @netman92 ?

**Comment by netman92** [comment]
In this case you can use any variable for controlling it. 

```python
configure_structlog(debug=env.get('testy'))
```

**Comment by aexvir** [comment]
Moved to GitLab
